routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::post('ckeditor','CkeditorController@upload')->name('ckeditor.upload');

Route::get('/dashboard', function () {
    return view('pages.dashboard.index');
})->middleware(['auth', 'verified'])->name('dashboard');


Route::group(['middleware' => 'auth'],function (){
    Route::resource('employee','EmployeeController',['names' => 'employee']);
    Route::resource('bonus','BonusController',['names' => 'bonus']);

    Route::get('profile', 'ProfileController@index');
    Route::post('profile/update-profile', 'ProfileController@updateProfile');
    Route::post('profile/update-password', 'ProfileController@updatePassword');
});
Route::resource('category','CategoryController',['names' => 'category']);


require __DIR__.'/auth.php';

app/Models/Bonus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bonus extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function employees()
    {
        return $this->hasMany(BonusEmployee::class);
    }
}

app/Http/Controllers/BonusController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\BonusRequest;
use App\Models\Bonus;
use App\Models\Category;
use App\Models\Employee;
use App\Services\BonusService;
use CrudAjax;
use Illuminate\Http\Request;
use DataTables;
use App\Http\Requests\CategoryRequest;

class BonusController extends CrudAjax
{
    protected $model  = Bonus::class;
    protected $url    = "bonus/";
    protected $folder = "pages.bonus.";
    protected $files  = false;
    private $facade;

    public function __construct(BonusService $facade)
    {
        $this->facade = $facade;
        parent::__construct($this);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            return $this->datatable($request);
        }

        return view($this->folder . "index");
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->model->with('employees')->findOrFail($id);
        return renderToJson($this->folder . "show",compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return renderToJson($this->folder . "create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BonusRequest $request)
    {
        return $this->setFacade($this->facade)->save();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->model->findOrFail($id);

        return renderToJson($this->folder . "edit", compact("data"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BonusRequest $request, $id)
    {
        return $this->setParams($id)
            ->setFacade($this->facade)
            ->change();
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->setParams($id)
            ->delete();
    }

    /**
     * json data for datatable.
     *
     *
     * @return DataTables
     */
    public function datatable($request)
    {
        $datas = $this->model->query();

        return DataTables::of($datas)
            ->addIndexColumn()
            ->editColumn('created_at', function ($data) {
                return date_indo($data->created_at);
            })
            ->editColumn('ammount', function ($data) {
                return  number_format($data->ammount, 0, ',', '.');
            })
            ->addColumn('action', function ($data) {
                $params = [
                    'data'        => $data,
                    'size'        => 'lg',
                    'url_show'    => url($this->url . $data->id),
                    'url_edit'    => url($this->url . $data->id . '/edit'),
                    'url_destroy' => url($this->url . $data->id),
                    'detele_title'=> "data",
                    'delete_text' => view($this->folder . 'delete', compact('data'))->render()
                ];
                if(auth()->user()->role == 'ADMIN'){
                    return view('components.datatables.action-with-show', $params);
                }else{
                    return view('components.datatables.show-only', $params);
                }
            })
            ->make(true);
    }

}

resources/views/pages/bonus/create.blade.php
<form   data-url="{{ route('bonus.store') }}" method="POST" class="needs-validation forms" novalidate>
    <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"> @lang('main.form.add')</h4>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close" data-bs-original-title="" title=""></button>
    </div>
    <div class="modal-body">
        <div class="errors"></div>

        @csrf

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Pembayaran <x-requiredmark /></label>
            <div class="col-sm-10">
                <input  type="text" class="form-control pembayaran_show" value="0" required>
                <input name="ammount" type="hidden" class="form-control pembayaran" value="0" required>
            </div>
        </div>

        <button type="button" class="btn btn-primary add-employee">
            <i class="fa fa-plus me-2"></i>
        </button>

        <div class="row">
            <div id="input-employees"></div>
        </div>

        <h3>Total</h3>
        <hr>
        <div class="row">
            <div id="list-bonuses"></div>
        </div>


    </div>
    <div class="modal-footer">

        <div class="loading" style="display: none;">
            <div class="spinner-border text-primary" role="status" style="width: 30px; height: 30px; margin-right:20px">
            </div>
        </div>

        <div class="button w-100">
            <div class="d-flex justify-content-between ">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal"> <i class="fa fa-reply-all"></i> @lang('main.button.cancel')</button>
                <button type="submit" class="btn btn-success "> <i class="fa fa-paper-plane"></i> @lang('main.button.save')</button>
            </div>
        </div>
    </div>
</form>

<script>
    var order = 1;
    autoNumericGlobal("pembayaran_show", "pembayaran")

    function validationAmmount(){
        var pembayaran = $('.pembayaran').val();

        if(pembayaran == 0){

            return false;
        }
        return true;
    }

    $('.add-employee').click(function (){
        var validate = validationAmmount();
        if(!validate){
            alert('Silahkan Input Nominal Pembayaran');
            return false;
        }

        // add dynamic input employee
        var input = `
                <div class="form-group row mt-0">

                    <div class="col-sm-6">
                        <label class="col-sm-12 col-form-label">Nama <x-requiredmark /></label>
                        <input name="name[]" type="text" class="form-control name-employee" data-order="`+order+`" required>
                    </div>

                    <div class="col-sm-2">
                        <label class="col-sm-12 col-form-label">Persen <x-requiredmark /></label>
                        <input name="percen[]" type="number"  class="form-control percen-employee" data-order="`+order+`" required>
                    </div>
                    <label class="col-sm-1 col-form-label mt-5">%</label>
                    <div class="col-sm-2 mt-5">
                        <button type="button" class="btn btn-danger delete-employee"> <i class="fa fa-remove"></i> </button>
                    </div>
                </div>`;


        $('#input-employees').append(input);



    //     add ammount list
        var ammounts = `
            <div class="row">
                    <div class="col-sm-1">
                        `+order+`.
                    </div>
                    <div class="col-sm-3">
                       <div class="name-employee-`+order+`"></div>
                    </div>
                    <div class="col-sm-7">
                       <div class="ammount-employee-`+order+`"></div>
                    </div>
            </div>`;

        $('#list-bonuses').append(ammounts);

        order++;


    });


    $(document).on('click', '.delete-employee', function(){
        $(this).parent().parent().remove()
    })

    $(document).on('keyup', '.name-employee', function(){
        var order = $(this).attr('data-order');

        var value = $(this).val();
        $('.name-employee-'+order).text(value);
    });

    $(document).on('keyup', '.percen-employee', function(){
        var order = $(this).attr('data-order');
        var totalAmmount = $('.pembayaran').val();

        var value = $(this).val();
        var percen = value / 100;
        total = percen * totalAmmount;
        $('.ammount-employee-'+order).text('Rp. ' + new Intl.NumberFormat('id-ID').format(total));
    });
</script>

resources/views/pages/bonus/delete.blade.php
<div>
    <table>
        <tr>
            <th>Name</th>
            <th>: {{ $data->name }}</th>
        </tr>
    </table>
</div>

resources/views/pages/bonus/edit.blade.php
<form   data-url="{{ route('bonus.update',['bonu' => $data]) }}" method="POST" class="needs-validation forms" novalidate>
    <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"> @lang('main.form.edit')</h4>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close" data-bs-original-title="" title=""></button>
    </div>
    <div class="modal-body">
        <div class="errors"></div>

        @csrf
        @method('PUT')

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Pembayaran <x-requiredmark /></label>
            <div class="col-sm-10">
                <input  type="text" class="form-control pembayaran_show" value="{{ $data->ammount }}" required>
                <input name="ammount" type="hidden" class="form-control pembayaran" value="{{ $data->ammount }}" required>
            </div>
        </div>

        <button type="button" class="btn btn-primary add-employee">
            <i class="fa fa-plus me-2"></i>
        </button>

        <div class="row">
            <div id="input-employees">
                @foreach($data->employees as $i => $employee)
                    <div class="form-group row mt-0">

                        <div class="col-sm-6">
                            <label class="col-sm-12 col-form-label">Nama <x-requiredmark /></label>
                            <input name="name[]" type="text" value="{{$employee->name}}" class="form-control name-employee" data-order="{{ $i+1 }}" required>
                        </div>

                        <div class="col-sm-2">
                            <label class="col-sm-12 col-form-label">Persen <x-requiredmark /></label>
                            <input name="percen[]" type="number" value="{{$employee->percen}}" class="form-control percen-employee" data-order="{{ $i+1 }}" required>
                        </div>
                        <label class="col-sm-1 col-form-label mt-5">%</label>
                        <div class="col-sm-2 mt-5">
                            <button type="button" class="btn btn-danger delete-employee"> <i class="fa fa-remove"></i> </button>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>

        <h3>Total</h3>
        <hr>
        <div class="row">
            <div id="list-bonuses">
                @foreach($data->employees as $i => $employee)
                    <div class="row">
                        <div class="col-sm-1">
                            {{ $i+1 }}.
                        </div>
                        <div class="col-sm-3">
                            <div class="name-employee-{{$i+1}}">{{ $employee->name }}</div>
                        </div>
                        <div class="col-sm-7">
                            <div class="ammount-employee-{{$i+1}}">Rp. {{ rupiah_format($employee->ammount) }}</div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>


    </div>
    <div class="modal-footer">

        <div class="loading" style="display: none;">
            <div class="spinner-border text-primary" role="status" style="width: 30px; height: 30px; margin-right:20px">
            </div>
        </div>

        <div class="button w-100">
            <div class="d-flex justify-content-between ">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal"> <i class="fa fa-reply-all"></i> @lang('main.button.cancel')</button>
                <button type="submit" class="btn btn-success "> <i class="fa fa-paper-plane"></i> @lang('main.button.edit')</button>
            </div>
        </div>
    </div>
</form>

<script>
    var order = "{{ count($data->employees)+1 }}";
    autoNumericGlobal("pembayaran_show", "pembayaran")

    function validationAmmount(){
        var pembayaran = $('.pembayaran').val();

        if(pembayaran == 0){

            return false;
        }
        return true;
    }

    $('.add-employee').click(function (){
        var validate = validationAmmount();
        if(!validate){
            alert('Silahkan Input Nominal Pembayaran');
            return false;
        }

        // add dynamic input employee
        var input = `
                <div class="form-group row mt-0">

                    <div class="col-sm-6">
                        <label class="col-sm-12 col-form-label">Nama <x-requiredmark /></label>
                        <input name="name[]" type="text" class="form-control name-employee" data-order="`+order+`" required>
                    </div>

                    <div class="col-sm-2">
                        <label class="col-sm-12 col-form-label">Persen <x-requiredmark /></label>
                        <input name="percen[]" type="number"  class="form-control percen-employee" data-order="`+order+`" required>
                    </div>
                    <label class="col-sm-1 col-form-label mt-5">%</label>
                    <div class="col-sm-2 mt-5">
                        <button type="button" class="btn btn-danger delete-employee"> <i class="fa fa-remove"></i> </button>
                    </div>
                </div>`;


        $('#input-employees').append(input);



        //     add ammount list
        var ammounts = `
            <div class="row">
                    <div class="col-sm-1">
                        `+order+`.
                    </div>
                    <div class="col-sm-3">
                       <div class="name-employee-`+order+`"></div>
                    </div>
                    <div class="col-sm-7">
                       <div class="ammount-employee-`+order+`"></div>
                    </div>
            </div>`;

        $('#list-bonuses').append(ammounts);

        order++;


    });


    $(document).on('click', '.delete-employee', function(){
        $(this).parent().parent().remove()
    })

    $(document).on('keyup', '.name-employee', function(){
        var order = $(this).attr('data-order');

        var value = $(this).val();
        $('.name-employee-'+order).text(value);
    });

    $(document).on('keyup', '.percen-employee', function(){
        var order = $(this).attr('data-order');
        var totalAmmount = $('.pembayaran').val();

        var value = $(this).val();
        var percen = value / 100;
        total = percen * totalAmmount;
        $('.ammount-employee-'+order).text('Rp. ' + new Intl.NumberFormat('id-ID').format(total));
    });
</script>

resources/views/pages/bonus/index.blade.php
@extends('layouts.admin.app')

@section("title","Bonus")

@section('page_styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/css/datatables.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/admin/js/sweetalert2/dist/sweetalert2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/admin/plugins/lightbox2/css/lightbox.css') }}">

@endsection

@section('content')

    <div class="card">
        <div class="card-header">
            <h5> Bonus </h5>
        </div>
        <div class="d-flex justify-content-between">
            <button class="btn btn-primary ms-4 show-form" data-url="{{ route('bonus.create') }}" data-size="lg">
                <i class="fa fa-plus"></i> Tambah
            </button>
        </div>
        <div class="card-body">

            <table id="myTable" class="table">
                <thead>
                <tr>
                    <th style="width: 100px;">No</th>
                    <th class="text-center">Tanggal</th>
                    <th class="text-center">Total (Rp)</th>
                    <th class="text-center" style="width: 200px;">Aksi</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>

    <x-modal  />
@endsection

@section('page_scripts')

    <script src="{{asset('assets/admin/js/datatable/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/admin/js/sweetalert2/dist/sweetalert2.min.js')}}"></script>
    <script src="{{asset('assets/admin/plugins/lightbox2/js/lightbox.js')}}"></script>
    <script src="{{ asset('assets/admin/plugins/AutoNumeric/AutoNumeric.js') }}"></script>
@endsection

@push('js')
    <script>

        $(document).ready(function() {

            var table = $('#myTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: '{{ route("bonus.index") }}' ,
                columns: [{
                    data: 'DT_RowIndex',
                    orderable: false,
                    searchable: false
                },
                    {

                        data: 'created_at'
                    },
                    {
                        class: 'text-end',
                        data: 'ammount'
                    },
                    {
                        data: 'action',
                        orderable: false,
                        searchable: false
                    }
                ]
            });
        });

        $('body').on("click", ".show-form", showForm);
        $('#modals').on("submit", ".forms", saveForm);
        $('body').on("click", ".btn_delete", deleteForm);
    </script>
@endpush

resources/views/pages/bonus/show.blade.php
<div>
    <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel"> @lang('main.form.detail')</h4>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close" data-bs-original-title="" title=""></button>
    </div>
    <div class="modal-body">
        <table class="table table-bordered table-striped table-hover">
            <tr>
                <th>Total</th>
                <td class="text-end" colspan="2">Rp.{{ rupiah_format($data->ammount) }}</td>
            </tr>
            <tr>
                <th colspan="3">List Pembayaran</th>
            </tr>
            <tr>
                <th>Nama</th>
                <th>Persen</th>
                <th>Jumlah</th>
            </tr>
            @foreach($data->employees as $employees)
                <tr>
                    <td>{{ $employees->name }}</td>
                    <td class="text-end">{{ $employees->percen }}%</td>
                    <td class="text-end">Rp.{{ rupiah_format($employees->ammount) }}</td>
                </tr>
            @endforeach

        </table>
    </div>
</div>